# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9.13'
    addToPath: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    # Run the shell script to install requirements
    cd environment_setup
    chmod +x install_requirements.sh
    ./install_requirements.sh
  displayName: 'Install Requirements'

- task: AzureCLI@1
  displayName: 'Create or Get Workspace'
  inputs:
    azureSubscription: 'Azure subscription 1 (21db576f-9f72-4aa6-ac5a-b26c33cd7e47)'
    scriptLocation: inlineScript
    inlineScript: 'python aml_service/00-Workspace.py'



