name: project_environment
channels:
  - defaults
dependencies:
  - python=3.9.13
  - psutil=5.9.0
  - pip
  - pip:
    - azure-cli==2.30.0
    - azureml-sdk[notebooks]    # add the version to lock it ==0.1.74
    - scipy==1.0.0
    - torch==2.2.2
    - torchvision==0.17.2
    - pytest==8.1.1